In [72]:
import pandas as pd
from io import StringIO
import sys

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,
14.0,,15.0,16.0'''


df = pd.read_csv(StringIO(csv_data))
df

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2  10.0  11.0  12.0   NaN
3  14.0   NaN  15.0  16.0

In [73]:
df.isnull().sum()

A    0
B    1
C    1
D    1
dtype: int64

In [74]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan],
       [14., nan, 15., 16.]])

In [75]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [76]:
df.dropna(axis=1)

      A
0   1.0
1   5.0
2  10.0
3  14.0

In [77]:
df.dropna(how='all')

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2  10.0  11.0  12.0   NaN
3  14.0   NaN  15.0  16.0

In [78]:
df.dropna(subset=['C'])

      A     B     C     D
0   1.0   2.0   3.0   4.0
2  10.0  11.0  12.0   NaN
3  14.0   NaN  15.0  16.0

In [79]:
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [80]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  3.,  8.],
       [10., 11., 12.,  4.],
       [14.,  2., 15., 16.]])

In [81]:
import pandas as pd
from io import StringIO
import sys

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,
14.0,,15.0,16.0'''


df = pd.read_csv(StringIO(csv_data))
df.fillna(df.mode().iloc[0], inplace=True)
df

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   3.0   8.0
2  10.0  11.0  12.0   4.0
3  14.0   2.0  15.0  16.0

In [82]:
df.fillna(df.mean(), inplace=True)
df

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   3.0   8.0
2  10.0  11.0  12.0   4.0
3  14.0   2.0  15.0  16.0

In [83]:

df.fillna(df.mode().iloc[0], inplace=True)
df

      A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   3.0   8.0
2  10.0  11.0  12.0   4.0
3  14.0   2.0  15.0  16.0

In [84]:
import pandas as pd

df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2'],
                   ['yellow', 'XL', 14.2, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

    color size  price classlabel
0   green    M   10.1     class2
1     red    L   13.5     class1
2    blue   XL   15.3     class2
3  yellow   XL   14.2     class2

In [85]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

df['size'] = df['size'].map(size_mapping)
df

    color  size  price classlabel
0   green     1   10.1     class2
1     red     2   13.5     class1
2    blue     3   15.3     class2
3  yellow     3   14.2     class2

In [86]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
3    XL
Name: size, dtype: object

In [87]:
import numpy as np

class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

df['classlabel'] = df['classlabel'].map(class_mapping)
df

    color  size  price  classlabel
0   green     1   10.1           1
1     red     2   13.5           0
2    blue     3   15.3           1
3  yellow     3   14.2           1

In [88]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

    color  size  price classlabel
0   green     1   10.1     class2
1     red     2   13.5     class1
2    blue     3   15.3     class2
3  yellow     3   14.2     class2

In [89]:
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1, 1])

In [90]:
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2', 'class2'], dtype=object)

In [91]:
class_le.classes_

array(['class1', 'class2'], dtype=object)

In [92]:
from sklearn.preprocessing import OneHotEncoder

X = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [93]:
X = df[['color', 'size', 'price']].values
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3],
       [3, 3, 14.2]], dtype=object)

In [94]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder(dtype=int)
col_trans = ColumnTransformer([('ord_enc', ord_enc, ['color'])])
X_trans = col_trans.fit_transform(df)
X_trans

array([[1],
       [2],
       [0],
       [3]])

In [95]:
col_trans.named_transformers_['ord_enc'].inverse_transform(X_trans)

array([['green'],
       ['red'],
       ['blue'],
       ['yellow']], dtype=object)

In [96]:
from sklearn.compose import ColumnTransformer

X = df[['color', 'size', 'price']].values
c_transf = ColumnTransformer([ ('onehot', OneHotEncoder(), [0]),
                               ('nothing', 'passthrough', [1, 2])])
c_transf.fit_transform(X)

array([[0.0, 1.0, 0.0, 0.0, 1, 10.1],
       [0.0, 0.0, 1.0, 0.0, 2, 13.5],
       [1.0, 0.0, 0.0, 0.0, 3, 15.3],
       [0.0, 0.0, 0.0, 1.0, 3, 14.2]], dtype=object)

In [100]:
c_transf = ColumnTransformer([ ('onehot', OneHotEncoder(dtype=int), [0]),
                               ('nothing', 'passthrough', [1, 2])])
c_transf.fit_transform(X)

array([[0, 1, 0, 0, 1, 10.1],
       [0, 0, 1, 0, 2, 13.5],
       [1, 0, 0, 0, 3, 15.3],
       [0, 0, 0, 1, 3, 14.2]], dtype=object)

In [101]:
pd.get_dummies(df[['price', 'color', 'size']])

   price  size  color_blue  color_green  color_red  color_yellow
0   10.1     1       False         True      False         False
1   13.5     2       False        False       True         False
2   15.3     3        True        False      False         False
3   14.2     3       False        False      False          True

In [104]:
dummies = pd.get_dummies(df[['price', 'color', 'size']])  
dummies[['color_blue', 'color_red', 'color_green']] = dummies[['color_blue', 'color_red', 'color_green']].astype(int)
print(dummies)

   price  size  color_blue  color_green  color_red  color_yellow
0   10.1     1           0            1          0         False
1   13.5     2           0            0          1         False
2   15.3     3           1            0          0         False
3   14.2     3           0            0          0          True